name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
      - run: npm run build --if-present
      - run: git config --global user.email "ishitwa2000@gmail.com"
      - run: git config --global user.name "IshitwaAgrawal"
      - run: git remote set-url origin https://${{secrets.ACTIONS_DEPLOY_ACCESS_TOKEN}}@github.com/${{github.repository}}
      - run: npm run deploy
