name: React app continuous integration

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
