name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build --if-present
      - run: git config --global user.email ${{secrets.MY_COOL_EMAIL}}
      - run: git config --global user.name ${{secrets.MY_COOL_USERNAME}}
      - run: git remote set-url origin https://${{secrets.ACTIONS_DEPLOY_ACCESS_TOKEN}}@github.com/${{github.repository}}
      - run: npm run deploy
