name: React app CI/CD

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - run: npm run build

      - run: git config --global user.name IshitwaAgrawal

      - run: git config --global user.email ishitwa2000@gmail.com

      - run: git remote set-url origin https://${github_token}@github.com/${repository}

      - run: npm run deploy

        env:
          user_name: "IshitwaAgrawal"
          user_email: "ishitwa2000@gmail.com"
          github_token: ${{secrets.ACTIONS_DEPLOY_ACCESS_TOKEN}}
          repository: ${{github.repository}}
